/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivePlan {
  'planId' : PlanId,
  'activatedAt' : bigint,
  'lastEarningsUpdate' : bigint,
}
export interface DepositRequest {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'user' : Principal,
  'submittedAt' : bigint,
  'utrNumber' : UTRNumber,
  'amount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FileContent { 'blob' : ExternalBlob, 'name' : string }
export interface Link {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'submittedBy' : string,
}
export type PaymentApp = { 'Paytm' : null } |
  { 'PhonePe' : null } |
  { 'GooglePay' : null };
export interface PaymentSubmission {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'planId' : PlanId,
  'user' : Principal,
  'submittedAt' : bigint,
  'utrNumber' : UTRNumber,
  'paymentApp' : PaymentApp,
}
export interface Plan {
  'id' : PlanId,
  'name' : string,
  'dailyEarning' : bigint,
  'validityDays' : bigint,
  'price' : bigint,
}
export type PlanId = bigint;
export interface Testimonial {
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
}
export type UTRNumber = string;
export interface User {
  'principal' : Principal,
  'joinDate' : bigint,
  'mobile' : string,
  'walletBalance' : bigint,
  'activePlan' : [] | [ActivePlan],
}
export interface UserProfile {
  'joinDate' : bigint,
  'mobile' : string,
  'walletBalance' : bigint,
  'activePlan' : [] | [ActivePlan],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'rejected' : null },
  'user' : Principal,
  'upiId' : string,
  'amount' : bigint,
  'requestedAt' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFile' : ActorMethod<[string, ExternalBlob], undefined>,
  'addLink' : ActorMethod<[string, string, string], undefined>,
  'addPlan' : ActorMethod<[string, bigint, bigint, bigint], PlanId>,
  'addTestimonial' : ActorMethod<[string, string], undefined>,
  'approveDepositRequest' : ActorMethod<[bigint], undefined>,
  'approvePaymentSubmission' : ActorMethod<[bigint], undefined>,
  'approveWithdrawalRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'ensureDefaultPlans' : ActorMethod<[], undefined>,
  'getAllDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getAllFiles' : ActorMethod<[], Array<FileContent>>,
  'getAllPaymentSubmissions' : ActorMethod<[], Array<PaymentSubmission>>,
  'getAllPlans' : ActorMethod<[], Array<Plan>>,
  'getAllWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getCallerDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getCallerProfileWithEarnings' : ActorMethod<[], User>,
  'getCallerReferralStats' : ActorMethod<
    [],
    { 'totalReferrals' : bigint, 'totalEarnings' : bigint }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFile' : ActorMethod<[string], [] | [FileContent]>,
  'getLinks' : ActorMethod<[], Array<Link>>,
  'getTestimonialByAuthor' : ActorMethod<[string], [] | [Testimonial]>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string], undefined>,
  'rejectDepositRequest' : ActorMethod<[bigint], undefined>,
  'rejectPaymentSubmission' : ActorMethod<[bigint], undefined>,
  'rejectWithdrawalRequest' : ActorMethod<[bigint], undefined>,
  'requestDeposit' : ActorMethod<[bigint, UTRNumber], undefined>,
  'requestPlanPurchase' : ActorMethod<
    [PlanId, PaymentApp, UTRNumber],
    undefined
  >,
  'requestWithdrawal' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setReferredBy' : ActorMethod<[string], undefined>,
  'updatePlan' : ActorMethod<[PlanId, string, bigint, bigint, bigint], Plan>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];