/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlanId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UTRNumber = IDL.Text;
export const DepositRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'utrNumber' : UTRNumber,
  'amount' : IDL.Nat,
});
export const PaymentApp = IDL.Variant({
  'Paytm' : IDL.Null,
  'PhonePe' : IDL.Null,
  'GooglePay' : IDL.Null,
});
export const PaymentSubmission = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'planId' : PlanId,
  'user' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'utrNumber' : UTRNumber,
  'paymentApp' : PaymentApp,
});
export const Plan = IDL.Record({
  'id' : PlanId,
  'name' : IDL.Text,
  'dailyEarning' : IDL.Nat,
  'validityDays' : IDL.Nat,
  'price' : IDL.Nat,
});
export const WithdrawalRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
  'requestedAt' : IDL.Int,
});
export const ActivePlan = IDL.Record({
  'planId' : PlanId,
  'activatedAt' : IDL.Int,
  'lastEarningsUpdate' : IDL.Int,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'joinDate' : IDL.Int,
  'mobile' : IDL.Text,
  'walletBalance' : IDL.Nat,
  'activePlan' : IDL.Opt(ActivePlan),
});
export const UserProfile = IDL.Record({
  'joinDate' : IDL.Int,
  'mobile' : IDL.Text,
  'walletBalance' : IDL.Nat,
  'activePlan' : IDL.Opt(ActivePlan),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlan' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [PlanId], []),
  'approveDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'approvePaymentSubmission' : IDL.Func([IDL.Nat], [], []),
  'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getAllPaymentSubmissions' : IDL.Func(
      [],
      [IDL.Vec(PaymentSubmission)],
      ['query'],
    ),
  'getAllPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getCallerProfileWithEarnings' : IDL.Func([], [User], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'rejectDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'rejectPaymentSubmission' : IDL.Func([IDL.Nat], [], []),
  'rejectWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
  'requestDeposit' : IDL.Func([IDL.Nat, UTRNumber], [], []),
  'requestPlanPurchase' : IDL.Func([PlanId, PaymentApp, UTRNumber], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePlan' : IDL.Func(
      [PlanId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [Plan],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlanId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UTRNumber = IDL.Text;
  const DepositRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'utrNumber' : UTRNumber,
    'amount' : IDL.Nat,
  });
  const PaymentApp = IDL.Variant({
    'Paytm' : IDL.Null,
    'PhonePe' : IDL.Null,
    'GooglePay' : IDL.Null,
  });
  const PaymentSubmission = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'planId' : PlanId,
    'user' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'utrNumber' : UTRNumber,
    'paymentApp' : PaymentApp,
  });
  const Plan = IDL.Record({
    'id' : PlanId,
    'name' : IDL.Text,
    'dailyEarning' : IDL.Nat,
    'validityDays' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
    'requestedAt' : IDL.Int,
  });
  const ActivePlan = IDL.Record({
    'planId' : PlanId,
    'activatedAt' : IDL.Int,
    'lastEarningsUpdate' : IDL.Int,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'joinDate' : IDL.Int,
    'mobile' : IDL.Text,
    'walletBalance' : IDL.Nat,
    'activePlan' : IDL.Opt(ActivePlan),
  });
  const UserProfile = IDL.Record({
    'joinDate' : IDL.Int,
    'mobile' : IDL.Text,
    'walletBalance' : IDL.Nat,
    'activePlan' : IDL.Opt(ActivePlan),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlan' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [PlanId], []),
    'approveDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'approvePaymentSubmission' : IDL.Func([IDL.Nat], [], []),
    'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getAllPaymentSubmissions' : IDL.Func(
        [],
        [IDL.Vec(PaymentSubmission)],
        ['query'],
      ),
    'getAllPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getCallerProfileWithEarnings' : IDL.Func([], [User], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'rejectDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'rejectPaymentSubmission' : IDL.Func([IDL.Nat], [], []),
    'rejectWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
    'requestDeposit' : IDL.Func([IDL.Nat, UTRNumber], [], []),
    'requestPlanPurchase' : IDL.Func([PlanId, PaymentApp, UTRNumber], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePlan' : IDL.Func(
        [PlanId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [Plan],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };