/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PlanId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UTRNumber = IDL.Text;
export const DepositRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'utrNumber' : UTRNumber,
  'amount' : IDL.Nat,
});
export const FileContent = IDL.Record({
  'blob' : ExternalBlob,
  'name' : IDL.Text,
});
export const PaymentApp = IDL.Variant({
  'Paytm' : IDL.Null,
  'PhonePe' : IDL.Null,
  'GooglePay' : IDL.Null,
});
export const PaymentSubmission = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'planId' : PlanId,
  'user' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'utrNumber' : UTRNumber,
  'paymentApp' : PaymentApp,
});
export const Plan = IDL.Record({
  'id' : PlanId,
  'name' : IDL.Text,
  'dailyEarning' : IDL.Nat,
  'validityDays' : IDL.Nat,
  'price' : IDL.Nat,
});
export const WithdrawalRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
  'requestedAt' : IDL.Int,
});
export const ActivePlan = IDL.Record({
  'planId' : PlanId,
  'activatedAt' : IDL.Int,
  'lastEarningsUpdate' : IDL.Int,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'joinDate' : IDL.Int,
  'mobile' : IDL.Text,
  'walletBalance' : IDL.Nat,
  'activePlan' : IDL.Opt(ActivePlan),
});
export const UserProfile = IDL.Record({
  'joinDate' : IDL.Int,
  'mobile' : IDL.Text,
  'walletBalance' : IDL.Nat,
  'activePlan' : IDL.Opt(ActivePlan),
});
export const Link = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'submittedBy' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFile' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'addLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPlan' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [PlanId], []),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'approveDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'approvePaymentSubmission' : IDL.Func([IDL.Nat], [], []),
  'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'ensureDefaultPlans' : IDL.Func([], [], []),
  'getAllDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileContent)], ['query']),
  'getAllPaymentSubmissions' : IDL.Func(
      [],
      [IDL.Vec(PaymentSubmission)],
      ['query'],
    ),
  'getAllPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getCallerDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(DepositRequest)],
      ['query'],
    ),
  'getCallerProfileWithEarnings' : IDL.Func([], [User], []),
  'getCallerReferralStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalReferrals' : IDL.Nat, 'totalEarnings' : IDL.Nat })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileContent)], ['query']),
  'getLinks' : IDL.Func([], [IDL.Vec(Link)], ['query']),
  'getTestimonialByAuthor' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Testimonial)],
      ['query'],
    ),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'rejectDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'rejectPaymentSubmission' : IDL.Func([IDL.Nat], [], []),
  'rejectWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
  'requestDeposit' : IDL.Func([IDL.Nat, UTRNumber], [], []),
  'requestPlanPurchase' : IDL.Func([PlanId, PaymentApp, UTRNumber], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setReferredBy' : IDL.Func([IDL.Text], [], []),
  'updatePlan' : IDL.Func(
      [PlanId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [Plan],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PlanId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UTRNumber = IDL.Text;
  const DepositRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'utrNumber' : UTRNumber,
    'amount' : IDL.Nat,
  });
  const FileContent = IDL.Record({ 'blob' : ExternalBlob, 'name' : IDL.Text });
  const PaymentApp = IDL.Variant({
    'Paytm' : IDL.Null,
    'PhonePe' : IDL.Null,
    'GooglePay' : IDL.Null,
  });
  const PaymentSubmission = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'planId' : PlanId,
    'user' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'utrNumber' : UTRNumber,
    'paymentApp' : PaymentApp,
  });
  const Plan = IDL.Record({
    'id' : PlanId,
    'name' : IDL.Text,
    'dailyEarning' : IDL.Nat,
    'validityDays' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
    'requestedAt' : IDL.Int,
  });
  const ActivePlan = IDL.Record({
    'planId' : PlanId,
    'activatedAt' : IDL.Int,
    'lastEarningsUpdate' : IDL.Int,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'joinDate' : IDL.Int,
    'mobile' : IDL.Text,
    'walletBalance' : IDL.Nat,
    'activePlan' : IDL.Opt(ActivePlan),
  });
  const UserProfile = IDL.Record({
    'joinDate' : IDL.Int,
    'mobile' : IDL.Text,
    'walletBalance' : IDL.Nat,
    'activePlan' : IDL.Opt(ActivePlan),
  });
  const Link = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'submittedBy' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFile' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'addLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPlan' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [PlanId], []),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'approveDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'approvePaymentSubmission' : IDL.Func([IDL.Nat], [], []),
    'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'ensureDefaultPlans' : IDL.Func([], [], []),
    'getAllDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileContent)], ['query']),
    'getAllPaymentSubmissions' : IDL.Func(
        [],
        [IDL.Vec(PaymentSubmission)],
        ['query'],
      ),
    'getAllPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getCallerDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getCallerProfileWithEarnings' : IDL.Func([], [User], []),
    'getCallerReferralStats' : IDL.Func(
        [],
        [IDL.Record({ 'totalReferrals' : IDL.Nat, 'totalEarnings' : IDL.Nat })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileContent)], ['query']),
    'getLinks' : IDL.Func([], [IDL.Vec(Link)], ['query']),
    'getTestimonialByAuthor' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Testimonial)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'rejectDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'rejectPaymentSubmission' : IDL.Func([IDL.Nat], [], []),
    'rejectWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
    'requestDeposit' : IDL.Func([IDL.Nat, UTRNumber], [], []),
    'requestPlanPurchase' : IDL.Func([PlanId, PaymentApp, UTRNumber], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setReferredBy' : IDL.Func([IDL.Text], [], []),
    'updatePlan' : IDL.Func(
        [PlanId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [Plan],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };